# Generated by Django 6.0.3 on 2026-08-19 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CR_Control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['regd_no']},
        ),
        migrations.AlterField(
            model_name='students',
            name='phone_no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
